import { createFileRoute, Link } from "@tanstack/react-router";
import { Navbar } from "@/components/landing/Navbar";
import { Footer } from "@/components/landing/Footer";
import { useState, useEffect } from "react";
import { FileText, UserCheck, Zap, Shield, Slash, Calendar } from "lucide-react";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms & Conditions — Pikadecks" },
      { name: "description", content: "Rules, agreements, and fair use guidelines for using PikaDecks. AI generation disclaimers and billing details." },
      { name: "robots", content: "index, follow" },
      { property: "og:title", content: "Terms & Conditions — Pikadecks" },
      { property: "og:description", content: "Rules and agreements for using Pikadecks." },
      { property: "og:url", content: "https://pikadecks.app/terms" },
      { property: "og:type", content: "article" },
    ],
    links: [{ rel: "canonical", href: "https://pikadecks.app/terms" }],
  }),
  component: TermsPage,
});

const termsSections = [
  {
    title: "1. Acceptance of Terms",
    icon: FileText,
    color: "bg-blue-100 text-blue-600 border-blue-200",
    text: "By creating an account, signing up, or using Pikadecks, you agree to be bound by these Terms & Conditions. If you do not agree to all of these terms, please do not use the application. We reserve the right to modify these terms at any time.",
  },
  {
    title: "2. Account Registration",
    icon: UserCheck,
    color: "bg-green-100 text-green-600 border-green-200",
    text: "When you register through Clerk, you must provide accurate, complete, and current information. You are solely responsible for maintaining the confidentiality of your credentials and for all activities that occur under your account.",
  },
  {
    title: "3. AI Generations & Accuracy",
    icon: Zap,
    color: "bg-yellow-100 text-yellow-600 border-yellow-200",
    text: "Pikadecks uses cutting-edge artificial intelligence to automatically generate learning materials, cards, and summaries. Please note the following guidelines:",
    bullets: [
      {
        bold: "AI Hallucinations:",
        text: " AI models are not infallible. Users should cross-reference and verify critical study information generated by the app before taking exams.",
      },
      {
        bold: "Fair Use Policies:",
        text: " Automated bulk generations or abuse of the generation APIs will result in temporary throttling or account suspension to ensure stable service for all users.",
      },
    ],
  },
  {
    title: "4. Intellectual Property",
    icon: Shield,
    color: "bg-rose-100 text-rose-600 border-rose-200",
    text: "The software, layout, designs, and brand of Pikadecks are owned exclusively by us. You retain all ownership rights to the original text, notes, and study guides you upload or input into the app. You grant Pikadecks a license to process your uploaded materials solely to generate study decks and flashcards for your learning profile.",
  },
  {
    title: "5. Account Termination",
    icon: Slash,
    color: "bg-purple-100 text-purple-600 border-purple-200",
    text: "We reserve the right, without notice and at our sole discretion, to terminate or suspend your access to the application in cases of fraud, abuse, violating acceptable use policies, or non-compliance with these terms.",
  },
];

function TermsPage() {
  const [isWebView, setIsWebView] = useState(false);

  useEffect(() => {
    if (typeof window !== "undefined") {
      setIsWebView(window.location.search.includes("webview=true"));
    }
  }, []);

  return (
    <main className="min-h-screen bg-[#FBF8F2] text-[#2A241D] pb-16 font-sans">
      {!isWebView && <Navbar />}

      {/* Brand Header */}
      <section className={`px-6 pb-8 ${isWebView ? "pt-8" : "pt-28 md:pt-32"}`}>
        <div className="mx-auto max-w-3xl">
          {!isWebView && (
            <Link
              to="/"
              className="inline-flex items-center gap-1.5 rounded-xl border border-[#111111] bg-white px-3 py-1.5 text-xs font-bold text-[#2A241D] shadow-[2px_2px_0_0_#111] hover:translate-y-[-1px] hover:shadow-[3px_3px_0_0_#111] active:translate-y-[1px] active:shadow-[1px_1px_0_0_#111] transition-all"
            >
              ← Back to home
            </Link>
          )}

          <div className="mt-6 flex flex-wrap items-center gap-3">
            <span className="inline-flex items-center gap-1.5 rounded-full border-2 border-[#111111]/10 bg-white px-3 py-1 text-xs font-bold shadow-[2px_2px_0_0_#111111]/5">
              📜 USER AGREEMENT
            </span>
            <span className="flex items-center gap-1 text-xs font-bold text-[#867E70]">
              <Calendar className="h-3.5 w-3.5" />
              LAST UPDATED: MAY 21, 2026
            </span>
          </div>

          <h1 className="mt-4 font-display text-3xl font-bold md:text-5xl tracking-tight leading-tight">
            Terms & Conditions
          </h1>

          <p className="mt-4 text-sm md:text-base leading-relaxed text-[#867E70] font-medium">
            Thank you for choosing Pikadecks to accelerate your learning. These Terms & Conditions outline the rules, rights, and responsibilities associated with using our flashcard application and study tools. Please read them thoroughly.
          </p>
        </div>
      </section>

      {/* Sections List */}
      <section className="px-6">
        <div className="mx-auto max-w-3xl space-y-6">
          {termsSections.map((s, idx) => {
            const Icon = s.icon;
            return (
              <article
                key={idx}
                className="group relative rounded-[2rem] border-2 border-[#111111] bg-white p-6 md:p-8 shadow-[6px_6px_0_0_#111111] hover:translate-y-[-1px] hover:shadow-[8px_8px_0_0_#111111] transition-all"
              >
                <div className="flex items-center gap-4 border-b border-[#111111]/10 pb-4 mb-4">
                  <div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border-2 border-[#111111] ${s.color} shadow-[2px_2px_0_0_#111]`}>
                    <Icon className="h-5 w-5" />
                  </div>
                  <h2 className="font-display text-lg md:text-xl font-bold text-[#2A241D]">
                    {s.title}
                  </h2>
                </div>

                <p className="text-sm md:text-base leading-relaxed text-[#2A241D]/90 font-medium">
                  {s.text}
                </p>

                {s.bullets && (
                  <ul className="mt-4 space-y-3">
                    {s.bullets.map((b, i) => (
                      <li key={i} className="flex gap-2 text-sm md:text-base leading-relaxed text-[#2A241D]/90 font-medium">
                        <span className="text-[#5B4FE6] mt-1.5 shrink-0 h-1.5 w-1.5 rounded-full bg-[#5B4FE6]" />
                        <span>
                          <strong className="text-[#2A241D] font-bold">{b.bold}</strong>
                          {b.text}
                        </span>
                      </li>
                    ))}
                  </ul>
                )}
              </article>
            );
          })}

          <div className="text-center pt-6">
            <p className="text-xs text-[#867E70] font-semibold">
              Thank you for choosing Pikadecks to accelerate your learning. If you have any questions about these terms, please contact support@pikadecks.com.
            </p>
          </div>
        </div>
      </section>

      {!isWebView && <Footer />}
    </main>
  );
}
