export const pikaAssets = {
  appIcon: require('../../assets/Pika/appIcon.png'),
  hiThere: require('../../assets/Pika/hi_there.png'),
  oops: require('../../assets/Pika/oops.png'),
  achievement: require('../../assets/Pika/achievement.png'),
  breaktime: require('../../assets/Pika/breaktime.png'),
  cool: require('../../assets/Pika/cool.png'),
  downloading: require('../../assets/Pika/downloading.png'),
  frustration: require('../../assets/Pika/frustration.png'),
  goalReached: require('../../assets/Pika/goal_reached.png'),
  goodJob: require('../../assets/Pika/good_job.png'),
  gotIt: require('../../assets/Pika/got_it.png'),
  hello: require('../../assets/Pika/hello.png'),
  hmm: require('../../assets/Pika/hmm.png'),
  letsGo: require('../../assets/Pika/lets_go.png'),
  loading: require('../../assets/Pika/loading.png'),
  loveIt: require('../../assets/Pika/love_it.png'),
  newDeck: require('../../assets/Pika/new_deck.png'),
  niceOne: require('../../assets/Pika/nice_one.png'),
  ohhh: require('../../assets/Pika/ohhh.png'),
  onFire: require('../../assets/Pika/on_fire.png'),
  perfect: require('../../assets/Pika/perfect.png'),
  pikadecksLogo: require('../../assets/Pika/pikadecks_logo.png'),
  restUp: require('../../assets/Pika/rest_up.png'),
  searching: require('../../assets/Pika/searching.png'),
  seeYou: require('../../assets/Pika/see_you.png'),
  siidWorking: require('../../assets/Pika/siid_working.png'),
  sleeping: require('../../assets/Pika/sleeping.png'),
  soSad: require('../../assets/Pika/so_sad.png'),
  soHappy: require('../../assets/Pika/so_happy.png'),
  studyTime: require('../../assets/Pika/study_time.png'),
  success: require('../../assets/Pika/success.png'),
  superPika: require('../../assets/Pika/super_pika.png'),
  thanks: require('../../assets/Pika/thanks.png'),
  unboxing: require('../../assets/Pika/unboxing.png'),
  uploading: require('../../assets/Pika/uploading.png'),
  yayDone: require('../../assets/Pika/yay_done.png'),
};

export type PikaAssetKey = keyof typeof pikaAssets;
