-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.plans (
  plan_id integer NOT NULL DEFAULT nextval('plans_plan_id_seq'::regclass),
  plan_name character varying NOT NULL,
  max_ai_generations integer DEFAULT 0,
  price numeric DEFAULT 0,
  CONSTRAINT plans_pkey PRIMARY KEY (plan_id)
);
CREATE TABLE public.imports (
  import_id integer NOT NULL DEFAULT nextval('imports_import_id_seq'::regclass),
  user_id integer,
  import_type character varying NOT NULL,
  source_title character varying,
  source_url text,
  uploaded_file_url text,
  raw_text text,
  status character varying DEFAULT 'processing'::character varying,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT imports_pkey PRIMARY KEY (import_id)
);
CREATE TABLE public.aimodels (
  model_id integer NOT NULL DEFAULT nextval('aimodels_model_id_seq'::regclass),
  provider_name character varying,
  model_name character varying,
  max_tokens integer,
  CONSTRAINT aimodels_pkey PRIMARY KEY (model_id)
);
CREATE TABLE public.aigenerations (
  generation_id integer NOT NULL DEFAULT nextval('aigenerations_generation_id_seq'::regclass),
  user_id integer,
  import_id integer,
  model_id integer,
  prompt_used text,
  generated_cards_count integer DEFAULT 0,
  tokens_used integer DEFAULT 0,
  generation_status character varying DEFAULT 'completed'::character varying,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT aigenerations_pkey PRIMARY KEY (generation_id),
  CONSTRAINT aigenerations_import_id_fkey FOREIGN KEY (import_id) REFERENCES public.imports(import_id),
  CONSTRAINT aigenerations_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.aimodels(model_id)
);
CREATE TABLE public.userstats (
  stat_id integer NOT NULL DEFAULT nextval('userstats_stat_id_seq'::regclass),
  user_id integer,
  current_streak integer DEFAULT 0,
  longest_streak integer DEFAULT 0,
  cards_reviewed integer DEFAULT 0,
  study_days integer DEFAULT 0,
  CONSTRAINT userstats_pkey PRIMARY KEY (stat_id)
);
CREATE TABLE public.usercardprogress (
  progress_id integer NOT NULL DEFAULT nextval('usercardprogress_progress_id_seq'::regclass),
  user_id integer,
  card_id integer,
  is_starred boolean DEFAULT false,
  is_mastered boolean DEFAULT false,
  confidence_level integer DEFAULT 0,
  last_reviewed date,
  CONSTRAINT usercardprogress_pkey PRIMARY KEY (progress_id)
);
CREATE TABLE public.users (
  user_id uuid NOT NULL DEFAULT gen_random_uuid(),
  clerk_user_id text NOT NULL UNIQUE,
  name text,
  email text NOT NULL UNIQUE,
  profile_pic text,
  plan_type text DEFAULT 'free'::text,
  created_at timestamp without time zone DEFAULT now(),
  account_status text NOT NULL DEFAULT 'active'::text,
  deletion_requested_at timestamp without time zone,
  delete_after timestamp without time zone,
  deletion_reason text,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp without time zone,
  scheduled_deletion_at timestamp without time zone,
  CONSTRAINT users_pkey PRIMARY KEY (user_id)
);
CREATE TABLE public.decks (
  deck_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  title text NOT NULL,
  description text,
  thumbnail_url text,
  visibility text DEFAULT 'private'::text,
  source_pdf_url text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  notes_content text,
  notes_image_urls ARRAY,
  CONSTRAINT decks_pkey PRIMARY KEY (deck_id),
  CONSTRAINT decks_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.cards (
  card_id uuid NOT NULL DEFAULT gen_random_uuid(),
  deck_id uuid,
  question text NOT NULL,
  answer text NOT NULL,
  explanation text,
  difficulty text DEFAULT 'medium'::text,
  card_type text DEFAULT 'text'::text,
  card_order integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  image_key text,
  image_width integer,
  image_height integer,
  image_type text,
  notes_image_key text,
  notes_image_width integer,
  notes_image_height integer,
  notes_image_type text,
  CONSTRAINT cards_pkey PRIMARY KEY (card_id),
  CONSTRAINT cards_deck_id_fkey FOREIGN KEY (deck_id) REFERENCES public.decks(deck_id)
);
CREATE TABLE public.user_card_progress (
  progress_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  card_id uuid,
  is_starred boolean DEFAULT false,
  is_mastered boolean DEFAULT false,
  confidence_level integer DEFAULT 0,
  last_reviewed timestamp without time zone,
  CONSTRAINT user_card_progress_pkey PRIMARY KEY (progress_id),
  CONSTRAINT user_card_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id),
  CONSTRAINT user_card_progress_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.cards(card_id)
);
CREATE TABLE public.reviews (
  review_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  card_id uuid,
  next_review_date timestamp without time zone,
  last_reviewed timestamp without time zone,
  ease_factor double precision DEFAULT 2.5,
  interval_days integer DEFAULT 0,
  review_count integer DEFAULT 0,
  deck_id uuid NOT NULL,
  repetitions integer NOT NULL DEFAULT 0,
  lapses integer NOT NULL DEFAULT 0,
  learning_state USER-DEFINED NOT NULL DEFAULT 'new'::learning_state,
  last_reviewed_at timestamp without time zone,
  next_review_at timestamp without time zone NOT NULL DEFAULT now(),
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT reviews_pkey PRIMARY KEY (review_id),
  CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id),
  CONSTRAINT reviews_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.cards(card_id),
  CONSTRAINT reviews_deck_id_fkey FOREIGN KEY (deck_id) REFERENCES public.decks(deck_id)
);
CREATE TABLE public.uploads (
  upload_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  file_url text NOT NULL,
  file_name text,
  file_type text,
  processing_status text DEFAULT 'processing'::text,
  extracted_text text,
  created_at timestamp without time zone DEFAULT now(),
  processing_stage text DEFAULT 'UPLOADED'::text,
  processing_progress integer NOT NULL DEFAULT 0,
  processing_error_code text,
  processing_error_message text,
  deck_id uuid,
  completed_at timestamp without time zone,
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  page_count integer,
  plan_at_upload text NOT NULL DEFAULT 'free'::text,
  content_hash text,
  extracted_text_hash text,
  token_estimate integer,
  cache_hit boolean NOT NULL DEFAULT false,
  cache_generation_id uuid,
  cleanup_status text NOT NULL DEFAULT 'none'::text,
  cleanup_reason text,
  cleanup_requested_at timestamp without time zone,
  delete_after timestamp without time zone,
  CONSTRAINT uploads_pkey PRIMARY KEY (upload_id),
  CONSTRAINT uploads_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id),
  CONSTRAINT uploads_deck_id_fkey FOREIGN KEY (deck_id) REFERENCES public.decks(deck_id)
);
CREATE TABLE public.ai_generations (
  generation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  upload_id uuid,
  prompt_used text,
  model_name text,
  generated_cards_count integer DEFAULT 0,
  tokens_used integer DEFAULT 0,
  generation_status text DEFAULT 'completed'::text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT ai_generations_pkey PRIMARY KEY (generation_id),
  CONSTRAINT ai_generations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id),
  CONSTRAINT ai_generations_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES public.uploads(upload_id)
);
CREATE TABLE public.user_stats (
  stat_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  cards_reviewed integer DEFAULT 0,
  study_days integer DEFAULT 0,
  consecutive_ignored_days integer DEFAULT 0,
  preferred_study_hour integer,
  CONSTRAINT user_stats_pkey PRIMARY KEY (stat_id),
  CONSTRAINT user_stats_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.referrals (
  referral_id uuid NOT NULL DEFAULT gen_random_uuid(),
  inviter_user_id uuid,
  invited_user_id uuid,
  referral_code text UNIQUE,
  reward_given boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT referrals_pkey PRIMARY KEY (referral_id),
  CONSTRAINT referrals_inviter_user_id_fkey FOREIGN KEY (inviter_user_id) REFERENCES public.users(user_id),
  CONSTRAINT referrals_invited_user_id_fkey FOREIGN KEY (invited_user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.review_history (
  history_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  card_id uuid,
  deck_id uuid,
  rating text NOT NULL CHECK (rating = ANY (ARRAY['again'::text, 'hard'::text, 'good'::text, 'easy'::text])),
  reviewed_at timestamp without time zone DEFAULT now(),
  reviewed_client_at timestamp without time zone,
  synced_at timestamp without time zone DEFAULT now(),
  CONSTRAINT review_history_pkey PRIMARY KEY (history_id),
  CONSTRAINT review_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id),
  CONSTRAINT review_history_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.cards(card_id),
  CONSTRAINT review_history_deck_id_fkey FOREIGN KEY (deck_id) REFERENCES public.decks(deck_id)
);
CREATE TABLE public.user_push_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  push_token text NOT NULL,
  platform text NOT NULL CHECK (platform = ANY (ARRAY['android'::text, 'ios'::text, 'web'::text, 'unknown'::text])),
  app_version text,
  is_active boolean NOT NULL DEFAULT true,
  last_seen_at timestamp without time zone NOT NULL DEFAULT now(),
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  device_id text,
  CONSTRAINT user_push_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT user_push_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.notification_settings (
  user_id uuid NOT NULL,
  daily_review_reminders boolean NOT NULL DEFAULT true,
  streak_notifications boolean NOT NULL DEFAULT true,
  achievement_notifications boolean NOT NULL DEFAULT true,
  overdue_notifications boolean NOT NULL DEFAULT true,
  quiet_hours_enabled boolean NOT NULL DEFAULT false,
  quiet_hours_start time without time zone DEFAULT '22:00:00'::time without time zone,
  quiet_hours_end time without time zone DEFAULT '07:00:00'::time without time zone,
  timezone text DEFAULT 'UTC'::text,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT notification_settings_pkey PRIMARY KEY (user_id),
  CONSTRAINT notification_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.notification_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  notification_type text NOT NULL CHECK (notification_type = ANY (ARRAY['daily_review'::text, 'overdue_review'::text, 'streak'::text, 'achievement'::text, 'flashcard_generation'::text, 'engagement_8am'::text, 'engagement_10am'::text, 'engagement_1pm'::text, 'engagement_6pm'::text, 'night_reminder_9pm'::text, 'streak_warning_1130pm'::text, 'night_achievement_9pm'::text, 'sleep_reminder_1130pm'::text])),
  title text NOT NULL,
  body text NOT NULL,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'sent'::text CHECK (status = ANY (ARRAY['sent'::text, 'failed'::text, 'opened'::text])),
  provider_message_id text,
  error_message text,
  idempotency_key text NOT NULL UNIQUE,
  sent_at timestamp without time zone NOT NULL DEFAULT now(),
  opened_at timestamp without time zone,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT notification_logs_pkey PRIMARY KEY (id),
  CONSTRAINT notification_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.user_achievements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  achievement_key text NOT NULL,
  achieved_at timestamp without time zone NOT NULL DEFAULT now(),
  notification_sent_at timestamp without time zone,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_achievements_pkey PRIMARY KEY (id),
  CONSTRAINT user_achievements_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.generation_jobs (
  job_id uuid NOT NULL DEFAULT gen_random_uuid(),
  upload_id uuid NOT NULL,
  user_id uuid NOT NULL,
  plan text NOT NULL DEFAULT 'free'::text,
  requested_cards integer NOT NULL DEFAULT 10,
  page_count integer,
  status text NOT NULL DEFAULT 'pending'::text,
  stage text NOT NULL DEFAULT 'UPLOADED'::text,
  progress integer NOT NULL DEFAULT 0,
  priority integer NOT NULL DEFAULT 100,
  total_chunks integer NOT NULL DEFAULT 0,
  completed_chunks integer NOT NULL DEFAULT 0,
  failed_chunks integer NOT NULL DEFAULT 0,
  total_prompt_tokens integer NOT NULL DEFAULT 0,
  total_completion_tokens integer NOT NULL DEFAULT 0,
  estimated_cost_usd numeric DEFAULT 0,
  error_code text,
  error_message text,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  completed_at timestamp without time zone,
  content_hash text,
  generation_settings_hash text,
  cache_generation_id uuid,
  queue_entered_at timestamp without time zone,
  worker_started_at timestamp without time zone,
  provider_strategy text NOT NULL DEFAULT 'groq_primary_gemini_secondary'::text,
  token_size_class text,
  summary_calls integer NOT NULL DEFAULT 0,
  card_calls integer NOT NULL DEFAULT 0,
  total_llm_calls integer NOT NULL DEFAULT 0,
  provider_call_breakdown jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT generation_jobs_pkey PRIMARY KEY (job_id),
  CONSTRAINT generation_jobs_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES public.uploads(upload_id),
  CONSTRAINT generation_jobs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.generation_chunks (
  chunk_id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid,
  upload_id uuid NOT NULL,
  chunk_index integer NOT NULL,
  page_start integer,
  page_end integer,
  heading text,
  text_hash text NOT NULL,
  text_s3_key text,
  chunk_text text,
  text_preview text,
  token_estimate integer,
  assigned_provider text,
  status text NOT NULL DEFAULT 'pending'::text,
  attempts integer NOT NULL DEFAULT 0,
  fallback_count integer NOT NULL DEFAULT 0,
  error_code text,
  error_message text,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT generation_chunks_pkey PRIMARY KEY (chunk_id),
  CONSTRAINT generation_chunks_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.generation_jobs(job_id),
  CONSTRAINT generation_chunks_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES public.uploads(upload_id)
);
CREATE TABLE public.chunk_summaries (
  summary_id uuid NOT NULL DEFAULT gen_random_uuid(),
  chunk_id uuid,
  job_id uuid,
  upload_id uuid,
  provider_name text NOT NULL,
  summary text NOT NULL,
  key_points jsonb NOT NULL DEFAULT '[]'::jsonb,
  prompt_tokens integer DEFAULT 0,
  completion_tokens integer DEFAULT 0,
  latency_ms integer,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT chunk_summaries_pkey PRIMARY KEY (summary_id),
  CONSTRAINT chunk_summaries_chunk_id_fkey FOREIGN KEY (chunk_id) REFERENCES public.generation_chunks(chunk_id),
  CONSTRAINT chunk_summaries_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.generation_jobs(job_id),
  CONSTRAINT chunk_summaries_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES public.uploads(upload_id)
);
CREATE TABLE public.extracted_concepts (
  concept_id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid,
  upload_id uuid,
  chunk_id uuid,
  concept_type text NOT NULL,
  term text NOT NULL,
  definition text,
  relationships jsonb NOT NULL DEFAULT '[]'::jsonb,
  examples jsonb NOT NULL DEFAULT '[]'::jsonb,
  importance_score numeric DEFAULT 0,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT extracted_concepts_pkey PRIMARY KEY (concept_id),
  CONSTRAINT extracted_concepts_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.generation_jobs(job_id),
  CONSTRAINT extracted_concepts_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES public.uploads(upload_id),
  CONSTRAINT extracted_concepts_chunk_id_fkey FOREIGN KEY (chunk_id) REFERENCES public.generation_chunks(chunk_id)
);
CREATE TABLE public.generated_cards (
  generated_card_id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid,
  upload_id uuid,
  chunk_id uuid,
  concept_id uuid,
  provider_name text,
  card_type text NOT NULL DEFAULT 'qa'::text,
  question text NOT NULL,
  answer text NOT NULL,
  explanation text,
  normalized_question text,
  quality_score numeric DEFAULT 0,
  duplicate_group text,
  status text NOT NULL DEFAULT 'staged'::text,
  rejection_reason text,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  image_url text,
  notes_image_url text,
  CONSTRAINT generated_cards_pkey PRIMARY KEY (generated_card_id),
  CONSTRAINT generated_cards_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.generation_jobs(job_id),
  CONSTRAINT generated_cards_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES public.uploads(upload_id),
  CONSTRAINT generated_cards_chunk_id_fkey FOREIGN KEY (chunk_id) REFERENCES public.generation_chunks(chunk_id),
  CONSTRAINT generated_cards_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES public.extracted_concepts(concept_id)
);
CREATE TABLE public.processing_events (
  event_id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid,
  upload_id uuid,
  chunk_id uuid,
  provider_name text,
  stage text NOT NULL,
  level text NOT NULL DEFAULT 'info'::text,
  code text,
  message text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT processing_events_pkey PRIMARY KEY (event_id),
  CONSTRAINT processing_events_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.generation_jobs(job_id),
  CONSTRAINT processing_events_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES public.uploads(upload_id),
  CONSTRAINT processing_events_chunk_id_fkey FOREIGN KEY (chunk_id) REFERENCES public.generation_chunks(chunk_id)
);
CREATE TABLE public.provider_health (
  provider_name text NOT NULL,
  status text NOT NULL DEFAULT 'CLOSED'::text CHECK (status = ANY (ARRAY['CLOSED'::text, 'OPEN'::text, 'HALF_OPEN'::text])),
  failure_count integer NOT NULL DEFAULT 0,
  success_count integer NOT NULL DEFAULT 0,
  average_latency_ms integer,
  requests_last_minute integer NOT NULL DEFAULT 0,
  tokens_last_minute integer NOT NULL DEFAULT 0,
  tokens_today integer NOT NULL DEFAULT 0,
  daily_token_limit integer,
  concurrent_requests integer NOT NULL DEFAULT 0,
  max_concurrent_requests integer NOT NULL DEFAULT 1,
  last_success timestamp without time zone,
  last_failure timestamp without time zone,
  cooldown_until timestamp without time zone,
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT provider_health_pkey PRIMARY KEY (provider_name)
);
CREATE TABLE public.user_generation_cache (
  generation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  content_hash text NOT NULL,
  generation_settings_hash text NOT NULL,
  source_token_estimate integer,
  requested_cards integer NOT NULL DEFAULT 10,
  generated_cards jsonb NOT NULL DEFAULT '[]'::jsonb,
  deck_title text,
  card_count integer NOT NULL DEFAULT 0,
  provider_summary jsonb NOT NULL DEFAULT '{}'::jsonb,
  total_prompt_tokens integer NOT NULL DEFAULT 0,
  total_completion_tokens integer NOT NULL DEFAULT 0,
  estimated_cost_usd numeric DEFAULT 0,
  created_from_upload_id uuid,
  created_from_job_id uuid,
  last_used_at timestamp without time zone,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_generation_cache_pkey PRIMARY KEY (generation_id),
  CONSTRAINT user_generation_cache_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id),
  CONSTRAINT user_generation_cache_created_from_upload_id_fkey FOREIGN KEY (created_from_upload_id) REFERENCES public.uploads(upload_id),
  CONSTRAINT user_generation_cache_created_from_job_id_fkey FOREIGN KEY (created_from_job_id) REFERENCES public.generation_jobs(job_id)
);
CREATE TABLE public.text_extraction_cache (
  extraction_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  file_hash text NOT NULL,
  content_hash text NOT NULL,
  page_count integer,
  token_estimate integer,
  extracted_text_preview text,
  extracted_text_s3_key text,
  created_from_upload_id uuid,
  last_used_at timestamp without time zone,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT text_extraction_cache_pkey PRIMARY KEY (extraction_id),
  CONSTRAINT text_extraction_cache_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id),
  CONSTRAINT text_extraction_cache_created_from_upload_id_fkey FOREIGN KEY (created_from_upload_id) REFERENCES public.uploads(upload_id)
);
CREATE TABLE public.provider_usage_events (
  usage_event_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  upload_id uuid,
  job_id uuid,
  chunk_id uuid,
  provider_name text NOT NULL,
  model_name text,
  request_type text NOT NULL DEFAULT 'chunk_generation'::text,
  prompt_tokens integer NOT NULL DEFAULT 0,
  completion_tokens integer NOT NULL DEFAULT 0,
  estimated_cost_usd numeric DEFAULT 0,
  latency_ms integer,
  status text NOT NULL DEFAULT 'success'::text,
  error_code text,
  retry_count integer NOT NULL DEFAULT 0,
  fallback_used boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT provider_usage_events_pkey PRIMARY KEY (usage_event_id),
  CONSTRAINT provider_usage_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id),
  CONSTRAINT provider_usage_events_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES public.uploads(upload_id),
  CONSTRAINT provider_usage_events_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.generation_jobs(job_id),
  CONSTRAINT provider_usage_events_chunk_id_fkey FOREIGN KEY (chunk_id) REFERENCES public.generation_chunks(chunk_id)
);
CREATE TABLE public.rate_limit_buckets (
  bucket_id uuid NOT NULL DEFAULT gen_random_uuid(),
  scope text NOT NULL CHECK (scope = ANY (ARRAY['user'::text, 'global'::text, 'provider'::text])),
  scope_key text NOT NULL,
  provider_name text,
  window_start timestamp without time zone NOT NULL,
  window_seconds integer NOT NULL,
  request_count integer NOT NULL DEFAULT 0,
  token_count integer NOT NULL DEFAULT 0,
  limit_requests integer,
  limit_tokens integer,
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT rate_limit_buckets_pkey PRIMARY KEY (bucket_id)
);
CREATE TABLE public.file_cleanup_jobs (
  cleanup_job_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  upload_id uuid,
  file_url text NOT NULL,
  storage_provider text NOT NULL DEFAULT 's3'::text,
  storage_bucket text,
  storage_key text,
  reason text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'deleted'::text, 'failed'::text, 'skipped'::text])),
  requested_at timestamp without time zone NOT NULL DEFAULT now(),
  delete_after timestamp without time zone NOT NULL,
  processed_at timestamp without time zone,
  error_message text,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT file_cleanup_jobs_pkey PRIMARY KEY (cleanup_job_id),
  CONSTRAINT file_cleanup_jobs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id),
  CONSTRAINT file_cleanup_jobs_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES public.uploads(upload_id)
);
CREATE TABLE public.youtube_generations (
  generation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  youtube_url text NOT NULL,
  video_id text,
  title text,
  languages jsonb NOT NULL DEFAULT '["en"]'::jsonb,
  transcript_length integer NOT NULL DEFAULT 0,
  transcript_hash text,
  requested_cards integer NOT NULL DEFAULT 10,
  provider_used text,
  provider_call_count integer NOT NULL DEFAULT 0,
  summary_call_count integer NOT NULL DEFAULT 0,
  card_call_count integer NOT NULL DEFAULT 0,
  generation_status text NOT NULL DEFAULT 'queued'::text CHECK (generation_status = ANY (ARRAY['queued'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  processing_stage text NOT NULL DEFAULT 'QUEUED'::text,
  processing_progress integer NOT NULL DEFAULT 0,
  error_code text,
  error_message text,
  deck_id uuid,
  cards_generated integer NOT NULL DEFAULT 0,
  generation_duration_ms integer,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  completed_at timestamp without time zone,
  CONSTRAINT youtube_generations_pkey PRIMARY KEY (generation_id),
  CONSTRAINT youtube_generations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id),
  CONSTRAINT youtube_generations_deck_id_fkey FOREIGN KEY (deck_id) REFERENCES public.decks(deck_id)
);
CREATE TABLE public.user_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  product_id text NOT NULL,
  purchase_token text NOT NULL,
  purchase_token_sha256 text NOT NULL UNIQUE,
  transaction_id text,
  platform text NOT NULL DEFAULT 'android'::text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'active'::text, 'cancelled'::text, 'expired'::text, 'in_grace_period'::text, 'on_hold'::text, 'unknown'::text])),
  expires_at timestamp without time zone,
  purchase_time timestamp without time zone,
  verified_at timestamp without time zone,
  raw_response jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  plan_type text NOT NULL DEFAULT 'pro'::text,
  subscription_id text,
  package_name text,
  purchase_date timestamp without time zone,
  expiry_date timestamp without time zone,
  auto_renewing boolean NOT NULL DEFAULT false,
  active boolean NOT NULL DEFAULT false,
  latest_notification_type text,
  CONSTRAINT user_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT user_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.billing_events (
  event_id uuid NOT NULL DEFAULT gen_random_uuid(),
  package_name text,
  product_id text,
  purchase_token_sha256 text,
  event_type text NOT NULL,
  event_time timestamp without time zone,
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT billing_events_pkey PRIMARY KEY (event_id)
);
CREATE TABLE public.user_ai_usage_quotas (
  user_id uuid NOT NULL,
  usage_count integer NOT NULL DEFAULT 0 CHECK (usage_count >= 0),
  quota_reset_at timestamp without time zone NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_ai_usage_quotas_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_ai_usage_quotas_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.account_deletion_audit_log (
  id integer NOT NULL DEFAULT nextval('account_deletion_audit_log_id_seq'::regclass),
  user_id uuid NOT NULL,
  action character varying NOT NULL,
  requested_at timestamp without time zone,
  restored_at timestamp without time zone,
  permanent_deletion_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT account_deletion_audit_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.oauth_clients (
  client_id text NOT NULL,
  client_secret_hash text,
  client_name text NOT NULL,
  redirect_uri text NOT NULL,
  scopes ARRAY NOT NULL DEFAULT '{}'::text[],
  active boolean NOT NULL DEFAULT true,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT oauth_clients_pkey PRIMARY KEY (client_id)
);
CREATE TABLE public.oauth_codes (
  code text NOT NULL,
  user_id uuid NOT NULL,
  client_id text NOT NULL,
  redirect_uri text NOT NULL,
  scope text NOT NULL,
  expires_at timestamp without time zone NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT oauth_codes_pkey PRIMARY KEY (code),
  CONSTRAINT oauth_codes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id),
  CONSTRAINT oauth_codes_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.oauth_clients(client_id)
);
CREATE TABLE public.oauth_grants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  client_id text NOT NULL,
  scope text NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT oauth_grants_pkey PRIMARY KEY (id),
  CONSTRAINT oauth_grants_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id),
  CONSTRAINT oauth_grants_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.oauth_clients(client_id)
);
CREATE TABLE public.refresh_tokens (
  token_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  client_id text NOT NULL,
  token_hash text NOT NULL UNIQUE,
  expires_at timestamp without time zone NOT NULL,
  revoked boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT refresh_tokens_pkey PRIMARY KEY (token_id),
  CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id),
  CONSTRAINT refresh_tokens_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.oauth_clients(client_id)
);
CREATE TABLE public.mcp_usage_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  client_id text NOT NULL,
  deck_id uuid,
  cards_created integer NOT NULL DEFAULT 0,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT mcp_usage_events_pkey PRIMARY KEY (id),
  CONSTRAINT mcp_usage_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id),
  CONSTRAINT mcp_usage_events_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.oauth_clients(client_id),
  CONSTRAINT mcp_usage_events_deck_id_fkey FOREIGN KEY (deck_id) REFERENCES public.decks(deck_id)
);
CREATE TABLE public.mcp_request_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  client_id text NOT NULL,
  idempotency_key text NOT NULL UNIQUE,
  status text NOT NULL,
  response jsonb,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT mcp_request_log_pkey PRIMARY KEY (id),
  CONSTRAINT mcp_request_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id),
  CONSTRAINT mcp_request_log_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.oauth_clients(client_id)
);
CREATE TABLE public.processed_pubsub_messages (
  message_id text NOT NULL,
  received_at timestamp without time zone NOT NULL DEFAULT now(),
  event_type text,
  purchase_token_hash text,
  CONSTRAINT processed_pubsub_messages_pkey PRIMARY KEY (message_id)
);
CREATE TABLE public.user_streaks (
  user_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'BROKEN'::text CHECK (status = ANY (ARRAY['ACTIVE'::text, 'FROZEN'::text, 'BROKEN'::text])),
  current_streak integer NOT NULL DEFAULT 0,
  longest_streak integer NOT NULL DEFAULT 0,
  protected_streak_value integer NOT NULL DEFAULT 0,
  last_study_date date,
  last_qualified_study_at timestamp with time zone,
  last_qualified_study_local_date date,
  user_timezone text NOT NULL DEFAULT 'UTC'::text,
  freeze_started_at timestamp with time zone,
  freeze_expires_at timestamp with time zone,
  broken_at timestamp with time zone,
  restore_tokens_earned integer NOT NULL DEFAULT 0,
  restore_tokens_monthly integer NOT NULL DEFAULT 0,
  monthly_restore_count integer NOT NULL DEFAULT 0,
  last_refill_month text,
  last_restore_at timestamp with time zone,
  shield_count integer NOT NULL DEFAULT 0,
  last_shield_refill_month text,
  last_shield_used_at timestamp with time zone,
  shield_used_for_local_date date,
  earned_restore_token_milestone integer NOT NULL DEFAULT 0,
  total_study_days integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_streaks_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_streaks_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.streak_events (
  event_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  event_type text NOT NULL,
  previous_status text,
  next_status text,
  previous_streak integer NOT NULL DEFAULT 0,
  next_streak integer NOT NULL DEFAULT 0,
  streak_value integer NOT NULL DEFAULT 0,
  study_session_id uuid,
  idempotency_key text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT streak_events_pkey PRIMARY KEY (event_id),
  CONSTRAINT streak_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.study_sessions (
  session_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  started_at timestamp with time zone,
  ended_at timestamp with time zone,
  cards_reviewed integer NOT NULL DEFAULT 0,
  minutes_studied numeric NOT NULL DEFAULT 0,
  qualified_for_streak boolean NOT NULL DEFAULT false,
  qualification_reason text,
  client_session_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT study_sessions_pkey PRIMARY KEY (session_id),
  CONSTRAINT study_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.streak_config (
  key text NOT NULL,
  value jsonb NOT NULL,
  environment text NOT NULL DEFAULT 'production'::text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT streak_config_pkey PRIMARY KEY (key)
);