import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { Navbar } from "@/components/landing/Navbar";
import { Footer } from "@/components/landing/Footer";
import { FinalCTA } from "@/components/landing/FinalCTA";
import { createSEOHead, createFAQSchema } from "@/lib/seo";
import { Search, Book, Shield, Brain, Library, Sparkles } from "lucide-react";

const pageTitle = "Public AI Flashcard Decks Directory | PikaDecks";
const pageDescription = "Browse and study public, AI-generated flashcard decks for biology, medical school, AWS cloud, GRE vocab, and college exams. Import directly to PikaDecks.";

export interface PublicDeck {
  id: string;
  title: string;
  description: string;
  category: string;
  cardCount: number;
  icon: string;
}

export const publicDecks: PublicDeck[] = [
  {
    id: "biology-101",
    title: "Biology 101: Cellular Structure & Processes",
    description: "Master animal and plant cell structures, organelles, photosynthesis, respiration, and cellular division concepts.",
    category: "Science",
    cardCount: 15,
    icon: "dna"
  },
  {
    id: "aws-solutions-architect",
    title: "AWS Solutions Architect Associate Prep",
    description: "Core cloud architecture concepts including EC2, VPC, S3, RDS, IAM, serverless, and fault-tolerant design.",
    category: "Technology",
    cardCount: 25,
    icon: "cloud"
  },
  {
    id: "gre-vocabulary",
    title: "GRE High-Frequency Vocabulary Wordlist",
    description: "Enhance your verbal reasoning score with these 50 essential vocabulary words, complete with definitions and context.",
    category: "Exams",
    cardCount: 50,
    icon: "book"
  },
  {
    id: "neet-physics-formulas",
    title: "NEET Physics: Mechanics & Wave Motion",
    description: "High-yield formulas and key conceptual questions for NEET/JEE physics exams. Kinetics, rotation, and sound waves.",
    category: "Science",
    cardCount: 30,
    icon: "gauge"
  },
  {
    id: "medical-terminology",
    title: "Medical Terminology & Anatomical Systems",
    description: "High-yield terminology, prefix/suffix meanings, anatomical planes, and system definitions for medical students.",
    category: "Medicine",
    cardCount: 40,
    icon: "pulse"
  }
];

const faqs = [
  {
    question: "Can I copy these decks to my own account?",
    answer: "Yes! Any public deck in our directory can be copied and customized in your personal PikaDecks library with a single click."
  },
  {
    question: "How are these public decks created?",
    answer: "These decks are generated using our advanced AI document parser from high-quality open textbooks, lecture syllabus parameters, and verified study sheets."
  }
];

// ItemList schema helper for search catalog listing
const itemListSchema = {
  "@context": "https://schema.org",
  "@type": "ItemList",
  name: "Public Study Flashcard Decks",
  description: pageDescription,
  numberOfItems: publicDecks.length,
  itemListElement: publicDecks.map((deck, idx) => ({
    "@type": "ListItem",
    position: idx + 1,
    url: `https://pikadecks.app/decks/${deck.id}`,
    name: deck.title
  }))
};

export const Route = createFileRoute("/decks/")({
  head: () => createSEOHead({
    title: pageTitle,
    description: pageDescription,
    urlPath: "/decks",
    schemas: [itemListSchema, createFAQSchema(faqs)]
  }),
  component: DecksDirectoryPage
});

function DecksDirectoryPage() {
  const [search, setSearch] = useState("");

  const filteredDecks = publicDecks.filter((deck) =>
    deck.title.toLowerCase().includes(search.toLowerCase()) ||
    deck.description.toLowerCase().includes(search.toLowerCase()) ||
    deck.category.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <main className="min-h-screen bg-background text-foreground">
      <Navbar />

      {/* Directory Hero */}
      <section className="relative overflow-hidden px-4 pt-24 pb-16 md:pt-32 md:pb-20">
        <div className="absolute inset-0 bg-radial-yellow" aria-hidden />
        <div className="absolute inset-0 bg-grid opacity-30" aria-hidden />
        <div className="relative mx-auto max-w-4xl text-center space-y-6">
          <div className="inline-flex items-center gap-1.5 rounded-full border-2 border-foreground/10 bg-card/85 px-4 py-1.5 text-xs font-bold backdrop-blur">
            <img src="/favicon.svg" alt="" className="h-3.5 w-3.5" aria-hidden />
            <span>STUDENT DECK REPOSITORY</span>
          </div>

          <h1 className="font-display text-4xl font-bold tracking-tight md:text-6xl text-foreground">
            Explore Free Public Flashcards
          </h1>

          <p className="mx-auto max-w-2xl text-muted-foreground text-base md:text-lg">
            Study curated flashcard decks generated by AI for popular subjects. Copy them instantly to your account, customize, and study on iOS, Android, or Web.
          </p>

          {/* Search Box */}
          <div className="mx-auto max-w-md pt-4">
            <div className="relative rounded-2xl border-2 border-brand-ink bg-card px-4 py-3 flex items-center gap-3">
              <Search className="h-5 w-5 text-muted-foreground shrink-0" />
              <input
                type="text"
                placeholder="Search biology, AWS, physics, GRE..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="w-full bg-transparent text-sm font-semibold text-foreground focus:outline-none"
              />
            </div>
          </div>
        </div>
      </section>

      {/* Decks Grid */}
      <section className="px-4 pb-20">
        <div className="mx-auto max-w-6xl">
          {filteredDecks.length === 0 ? (
            <div className="text-center py-16 border-2 border-dashed border-foreground/10 rounded-3xl bg-card">
              <p className="text-muted-foreground font-semibold">No study decks found matching "{search}"</p>
            </div>
          ) : (
            <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
              {filteredDecks.map((deck) => (
                <article
                  key={deck.id}
                  className="group relative flex flex-col justify-between rounded-3xl border-2 border-foreground bg-card p-6 hover:translate-y-[-2px] transition-transform"
                >
                  <div className="space-y-4">
                    <div className="flex items-center justify-between">
                      <span className="rounded-full bg-brand-yellow/20 px-3 py-1 text-xs font-bold text-brand-ink dark:text-brand-yellow">
                        {deck.category}
                      </span>
                      <span className="text-xs font-semibold text-muted-foreground">
                        {deck.cardCount} Cards
                      </span>
                    </div>

                    <div>
                      <h3 className="font-display text-xl font-bold group-hover:text-brand-red transition-colors">
                        <Link to="/decks/$deckId" params={{ deckId: deck.id }}>{deck.title}</Link>
                      </h3>
                      <p className="mt-2 text-sm text-muted-foreground leading-relaxed line-clamp-3">
                        {deck.description}
                      </p>
                    </div>
                  </div>

                  <div className="mt-6 pt-4 border-t border-foreground/10 flex items-center justify-between">
                    <Link
                      to="/decks/$deckId"
                      params={{ deckId: deck.id }}
                      className="text-xs font-bold text-foreground hover:underline"
                    >
                      Preview Deck →
                    </Link>

                    <a
                      href="#cta"
                      className="inline-flex items-center gap-1 rounded-xl bg-brand-yellow px-3 py-1.5 text-xs font-bold text-brand-ink border border-brand-ink"
                    >
                      <Sparkles className="h-3 w-3" />
                      Import
                    </a>
                  </div>
                </article>
              ))}
            </div>
          )}
        </div>
      </section>

      {/* FAQs */}
      <section className="px-4 py-16 bg-card/40 border-t-2 border-foreground/10">
        <div className="mx-auto max-w-3xl space-y-8">
          <h2 className="font-display text-2xl font-bold text-center">Frequently Asked Questions</h2>
          <div className="space-y-6">
            {faqs.map((faq, idx) => (
              <div key={idx} className="rounded-2xl border border-foreground/10 bg-card p-6">
                <h3 className="font-display text-lg font-bold">{faq.question}</h3>
                <p className="mt-2 text-sm text-muted-foreground leading-relaxed">{faq.answer}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <FinalCTA />
      <Footer />
    </main>
  );
}
