/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YoutubeToFlashcardsRouteImport } from './routes/youtube-to-flashcards'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SpacedRepetitionAppRouteImport } from './routes/spaced-repetition-app'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as QuizletAlternativeRouteImport } from './routes/quizlet-alternative'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PdfToFlashcardsRouteImport } from './routes/pdf-to-flashcards'
import { Route as MedicalStudentStudyAppRouteImport } from './routes/medical-student-study-app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FlashcardGeneratorRouteImport } from './routes/flashcard-generator'
import { Route as DocumentationMcpRouteImport } from './routes/documentation-mcp'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BestAiStudyAppRouteImport } from './routes/best-ai-study-app'
import { Route as AnkiAlternativeRouteImport } from './routes/anki-alternative'
import { Route as AiStudyToolForCollegeStudentsRouteImport } from './routes/ai-study-tool-for-college-students'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DecksIndexRouteImport } from './routes/decks/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as DownloadsPikadecksDotapkRouteImport } from './routes/downloads.pikadecks[.]apk'
import { Route as DecksDeckIdRouteImport } from './routes/decks/$deckId'
import { Route as DashboardUploadRouteImport } from './routes/dashboard/upload'
import { Route as DashboardStreakRouteImport } from './routes/dashboard/streak'
import { Route as DashboardStatsRouteImport } from './routes/dashboard/stats'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardDecksRouteImport } from './routes/dashboard/decks'
import { Route as DashboardCreateYoutubeRouteImport } from './routes/dashboard/create-youtube'
import { Route as DashboardCreateNotesRouteImport } from './routes/dashboard/create-notes'
import { Route as DashboardConnectedAppsRouteImport } from './routes/dashboard/connected-apps'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardReviewStartRouteImport } from './routes/dashboard/review.start'
import { Route as DashboardReviewDeckIdRouteImport } from './routes/dashboard/review.$deckId'
import { Route as DashboardDeckDeckIdRouteImport } from './routes/dashboard/deck.$deckId'
import { Route as DashboardBillingHistoryRouteImport } from './routes/dashboard/billing.history'

const YoutubeToFlashcardsRoute = YoutubeToFlashcardsRouteImport.update({
  id: '/youtube-to-flashcards',
  path: '/youtube-to-flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacedRepetitionAppRoute = SpacedRepetitionAppRouteImport.update({
  id: '/spaced-repetition-app',
  path: '/spaced-repetition-app',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizletAlternativeRoute = QuizletAlternativeRouteImport.update({
  id: '/quizlet-alternative',
  path: '/quizlet-alternative',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToFlashcardsRoute = PdfToFlashcardsRouteImport.update({
  id: '/pdf-to-flashcards',
  path: '/pdf-to-flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalStudentStudyAppRoute = MedicalStudentStudyAppRouteImport.update({
  id: '/medical-student-study-app',
  path: '/medical-student-study-app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardGeneratorRoute = FlashcardGeneratorRouteImport.update({
  id: '/flashcard-generator',
  path: '/flashcard-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationMcpRoute = DocumentationMcpRouteImport.update({
  id: '/documentation-mcp',
  path: '/documentation-mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BestAiStudyAppRoute = BestAiStudyAppRouteImport.update({
  id: '/best-ai-study-app',
  path: '/best-ai-study-app',
  getParentRoute: () => rootRouteImport,
} as any)
const AnkiAlternativeRoute = AnkiAlternativeRouteImport.update({
  id: '/anki-alternative',
  path: '/anki-alternative',
  getParentRoute: () => rootRouteImport,
} as any)
const AiStudyToolForCollegeStudentsRoute =
  AiStudyToolForCollegeStudentsRouteImport.update({
    id: '/ai-study-tool-for-college-students',
    path: '/ai-study-tool-for-college-students',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksIndexRoute = DecksIndexRouteImport.update({
  id: '/decks/',
  path: '/decks/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsPikadecksDotapkRoute =
  DownloadsPikadecksDotapkRouteImport.update({
    id: '/downloads/pikadecks.apk',
    path: '/downloads/pikadecks.apk',
    getParentRoute: () => rootRouteImport,
  } as any)
const DecksDeckIdRoute = DecksDeckIdRouteImport.update({
  id: '/decks/$deckId',
  path: '/decks/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUploadRoute = DashboardUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStreakRoute = DashboardStreakRouteImport.update({
  id: '/streak',
  path: '/streak',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStatsRoute = DashboardStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDecksRoute = DashboardDecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCreateYoutubeRoute = DashboardCreateYoutubeRouteImport.update({
  id: '/create-youtube',
  path: '/create-youtube',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCreateNotesRoute = DashboardCreateNotesRouteImport.update({
  id: '/create-notes',
  path: '/create-notes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConnectedAppsRoute = DashboardConnectedAppsRouteImport.update({
  id: '/connected-apps',
  path: '/connected-apps',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewStartRoute = DashboardReviewStartRouteImport.update({
  id: '/review/start',
  path: '/review/start',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewDeckIdRoute = DashboardReviewDeckIdRouteImport.update({
  id: '/review/$deckId',
  path: '/review/$deckId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeckDeckIdRoute = DashboardDeckDeckIdRouteImport.update({
  id: '/deck/$deckId',
  path: '/deck/$deckId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingHistoryRoute = DashboardBillingHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardBillingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-study-tool-for-college-students': typeof AiStudyToolForCollegeStudentsRoute
  '/anki-alternative': typeof AnkiAlternativeRoute
  '/best-ai-study-app': typeof BestAiStudyAppRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/delete-account': typeof DeleteAccountRoute
  '/documentation-mcp': typeof DocumentationMcpRoute
  '/flashcard-generator': typeof FlashcardGeneratorRoute
  '/login': typeof LoginRoute
  '/medical-student-study-app': typeof MedicalStudentStudyAppRoute
  '/pdf-to-flashcards': typeof PdfToFlashcardsRoute
  '/privacy': typeof PrivacyRoute
  '/quizlet-alternative': typeof QuizletAlternativeRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spaced-repetition-app': typeof SpacedRepetitionAppRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/youtube-to-flashcards': typeof YoutubeToFlashcardsRoute
  '/dashboard/billing': typeof DashboardBillingRouteWithChildren
  '/dashboard/connected-apps': typeof DashboardConnectedAppsRoute
  '/dashboard/create-notes': typeof DashboardCreateNotesRoute
  '/dashboard/create-youtube': typeof DashboardCreateYoutubeRoute
  '/dashboard/decks': typeof DashboardDecksRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/dashboard/streak': typeof DashboardStreakRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/downloads/pikadecks.apk': typeof DownloadsPikadecksDotapkRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/decks/': typeof DecksIndexRoute
  '/dashboard/billing/history': typeof DashboardBillingHistoryRoute
  '/dashboard/deck/$deckId': typeof DashboardDeckDeckIdRoute
  '/dashboard/review/$deckId': typeof DashboardReviewDeckIdRoute
  '/dashboard/review/start': typeof DashboardReviewStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-study-tool-for-college-students': typeof AiStudyToolForCollegeStudentsRoute
  '/anki-alternative': typeof AnkiAlternativeRoute
  '/best-ai-study-app': typeof BestAiStudyAppRoute
  '/contact': typeof ContactRoute
  '/delete-account': typeof DeleteAccountRoute
  '/documentation-mcp': typeof DocumentationMcpRoute
  '/flashcard-generator': typeof FlashcardGeneratorRoute
  '/login': typeof LoginRoute
  '/medical-student-study-app': typeof MedicalStudentStudyAppRoute
  '/pdf-to-flashcards': typeof PdfToFlashcardsRoute
  '/privacy': typeof PrivacyRoute
  '/quizlet-alternative': typeof QuizletAlternativeRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spaced-repetition-app': typeof SpacedRepetitionAppRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/youtube-to-flashcards': typeof YoutubeToFlashcardsRoute
  '/dashboard/billing': typeof DashboardBillingRouteWithChildren
  '/dashboard/connected-apps': typeof DashboardConnectedAppsRoute
  '/dashboard/create-notes': typeof DashboardCreateNotesRoute
  '/dashboard/create-youtube': typeof DashboardCreateYoutubeRoute
  '/dashboard/decks': typeof DashboardDecksRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/dashboard/streak': typeof DashboardStreakRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/downloads/pikadecks.apk': typeof DownloadsPikadecksDotapkRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/dashboard': typeof DashboardIndexRoute
  '/decks': typeof DecksIndexRoute
  '/dashboard/billing/history': typeof DashboardBillingHistoryRoute
  '/dashboard/deck/$deckId': typeof DashboardDeckDeckIdRoute
  '/dashboard/review/$deckId': typeof DashboardReviewDeckIdRoute
  '/dashboard/review/start': typeof DashboardReviewStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-study-tool-for-college-students': typeof AiStudyToolForCollegeStudentsRoute
  '/anki-alternative': typeof AnkiAlternativeRoute
  '/best-ai-study-app': typeof BestAiStudyAppRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/delete-account': typeof DeleteAccountRoute
  '/documentation-mcp': typeof DocumentationMcpRoute
  '/flashcard-generator': typeof FlashcardGeneratorRoute
  '/login': typeof LoginRoute
  '/medical-student-study-app': typeof MedicalStudentStudyAppRoute
  '/pdf-to-flashcards': typeof PdfToFlashcardsRoute
  '/privacy': typeof PrivacyRoute
  '/quizlet-alternative': typeof QuizletAlternativeRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spaced-repetition-app': typeof SpacedRepetitionAppRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/youtube-to-flashcards': typeof YoutubeToFlashcardsRoute
  '/dashboard/billing': typeof DashboardBillingRouteWithChildren
  '/dashboard/connected-apps': typeof DashboardConnectedAppsRoute
  '/dashboard/create-notes': typeof DashboardCreateNotesRoute
  '/dashboard/create-youtube': typeof DashboardCreateYoutubeRoute
  '/dashboard/decks': typeof DashboardDecksRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/dashboard/streak': typeof DashboardStreakRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/downloads/pikadecks.apk': typeof DownloadsPikadecksDotapkRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/decks/': typeof DecksIndexRoute
  '/dashboard/billing/history': typeof DashboardBillingHistoryRoute
  '/dashboard/deck/$deckId': typeof DashboardDeckDeckIdRoute
  '/dashboard/review/$deckId': typeof DashboardReviewDeckIdRoute
  '/dashboard/review/start': typeof DashboardReviewStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-study-tool-for-college-students'
    | '/anki-alternative'
    | '/best-ai-study-app'
    | '/contact'
    | '/dashboard'
    | '/delete-account'
    | '/documentation-mcp'
    | '/flashcard-generator'
    | '/login'
    | '/medical-student-study-app'
    | '/pdf-to-flashcards'
    | '/privacy'
    | '/quizlet-alternative'
    | '/signup'
    | '/sitemap.xml'
    | '/spaced-repetition-app'
    | '/support'
    | '/terms'
    | '/youtube-to-flashcards'
    | '/dashboard/billing'
    | '/dashboard/connected-apps'
    | '/dashboard/create-notes'
    | '/dashboard/create-youtube'
    | '/dashboard/decks'
    | '/dashboard/profile'
    | '/dashboard/stats'
    | '/dashboard/streak'
    | '/dashboard/upload'
    | '/decks/$deckId'
    | '/downloads/pikadecks.apk'
    | '/oauth/consent'
    | '/dashboard/'
    | '/decks/'
    | '/dashboard/billing/history'
    | '/dashboard/deck/$deckId'
    | '/dashboard/review/$deckId'
    | '/dashboard/review/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-study-tool-for-college-students'
    | '/anki-alternative'
    | '/best-ai-study-app'
    | '/contact'
    | '/delete-account'
    | '/documentation-mcp'
    | '/flashcard-generator'
    | '/login'
    | '/medical-student-study-app'
    | '/pdf-to-flashcards'
    | '/privacy'
    | '/quizlet-alternative'
    | '/signup'
    | '/sitemap.xml'
    | '/spaced-repetition-app'
    | '/support'
    | '/terms'
    | '/youtube-to-flashcards'
    | '/dashboard/billing'
    | '/dashboard/connected-apps'
    | '/dashboard/create-notes'
    | '/dashboard/create-youtube'
    | '/dashboard/decks'
    | '/dashboard/profile'
    | '/dashboard/stats'
    | '/dashboard/streak'
    | '/dashboard/upload'
    | '/decks/$deckId'
    | '/downloads/pikadecks.apk'
    | '/oauth/consent'
    | '/dashboard'
    | '/decks'
    | '/dashboard/billing/history'
    | '/dashboard/deck/$deckId'
    | '/dashboard/review/$deckId'
    | '/dashboard/review/start'
  id:
    | '__root__'
    | '/'
    | '/ai-study-tool-for-college-students'
    | '/anki-alternative'
    | '/best-ai-study-app'
    | '/contact'
    | '/dashboard'
    | '/delete-account'
    | '/documentation-mcp'
    | '/flashcard-generator'
    | '/login'
    | '/medical-student-study-app'
    | '/pdf-to-flashcards'
    | '/privacy'
    | '/quizlet-alternative'
    | '/signup'
    | '/sitemap.xml'
    | '/spaced-repetition-app'
    | '/support'
    | '/terms'
    | '/youtube-to-flashcards'
    | '/dashboard/billing'
    | '/dashboard/connected-apps'
    | '/dashboard/create-notes'
    | '/dashboard/create-youtube'
    | '/dashboard/decks'
    | '/dashboard/profile'
    | '/dashboard/stats'
    | '/dashboard/streak'
    | '/dashboard/upload'
    | '/decks/$deckId'
    | '/downloads/pikadecks.apk'
    | '/oauth/consent'
    | '/dashboard/'
    | '/decks/'
    | '/dashboard/billing/history'
    | '/dashboard/deck/$deckId'
    | '/dashboard/review/$deckId'
    | '/dashboard/review/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiStudyToolForCollegeStudentsRoute: typeof AiStudyToolForCollegeStudentsRoute
  AnkiAlternativeRoute: typeof AnkiAlternativeRoute
  BestAiStudyAppRoute: typeof BestAiStudyAppRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DeleteAccountRoute: typeof DeleteAccountRoute
  DocumentationMcpRoute: typeof DocumentationMcpRoute
  FlashcardGeneratorRoute: typeof FlashcardGeneratorRoute
  LoginRoute: typeof LoginRoute
  MedicalStudentStudyAppRoute: typeof MedicalStudentStudyAppRoute
  PdfToFlashcardsRoute: typeof PdfToFlashcardsRoute
  PrivacyRoute: typeof PrivacyRoute
  QuizletAlternativeRoute: typeof QuizletAlternativeRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpacedRepetitionAppRoute: typeof SpacedRepetitionAppRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  YoutubeToFlashcardsRoute: typeof YoutubeToFlashcardsRoute
  DecksDeckIdRoute: typeof DecksDeckIdRoute
  DownloadsPikadecksDotapkRoute: typeof DownloadsPikadecksDotapkRoute
  OauthConsentRoute: typeof OauthConsentRoute
  DecksIndexRoute: typeof DecksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youtube-to-flashcards': {
      id: '/youtube-to-flashcards'
      path: '/youtube-to-flashcards'
      fullPath: '/youtube-to-flashcards'
      preLoaderRoute: typeof YoutubeToFlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaced-repetition-app': {
      id: '/spaced-repetition-app'
      path: '/spaced-repetition-app'
      fullPath: '/spaced-repetition-app'
      preLoaderRoute: typeof SpacedRepetitionAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizlet-alternative': {
      id: '/quizlet-alternative'
      path: '/quizlet-alternative'
      fullPath: '/quizlet-alternative'
      preLoaderRoute: typeof QuizletAlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-flashcards': {
      id: '/pdf-to-flashcards'
      path: '/pdf-to-flashcards'
      fullPath: '/pdf-to-flashcards'
      preLoaderRoute: typeof PdfToFlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-student-study-app': {
      id: '/medical-student-study-app'
      path: '/medical-student-study-app'
      fullPath: '/medical-student-study-app'
      preLoaderRoute: typeof MedicalStudentStudyAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcard-generator': {
      id: '/flashcard-generator'
      path: '/flashcard-generator'
      fullPath: '/flashcard-generator'
      preLoaderRoute: typeof FlashcardGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation-mcp': {
      id: '/documentation-mcp'
      path: '/documentation-mcp'
      fullPath: '/documentation-mcp'
      preLoaderRoute: typeof DocumentationMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-ai-study-app': {
      id: '/best-ai-study-app'
      path: '/best-ai-study-app'
      fullPath: '/best-ai-study-app'
      preLoaderRoute: typeof BestAiStudyAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anki-alternative': {
      id: '/anki-alternative'
      path: '/anki-alternative'
      fullPath: '/anki-alternative'
      preLoaderRoute: typeof AnkiAlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-study-tool-for-college-students': {
      id: '/ai-study-tool-for-college-students'
      path: '/ai-study-tool-for-college-students'
      fullPath: '/ai-study-tool-for-college-students'
      preLoaderRoute: typeof AiStudyToolForCollegeStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/': {
      id: '/decks/'
      path: '/decks'
      fullPath: '/decks/'
      preLoaderRoute: typeof DecksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads/pikadecks.apk': {
      id: '/downloads/pikadecks.apk'
      path: '/downloads/pikadecks.apk'
      fullPath: '/downloads/pikadecks.apk'
      preLoaderRoute: typeof DownloadsPikadecksDotapkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId': {
      id: '/decks/$deckId'
      path: '/decks/$deckId'
      fullPath: '/decks/$deckId'
      preLoaderRoute: typeof DecksDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/upload': {
      id: '/dashboard/upload'
      path: '/upload'
      fullPath: '/dashboard/upload'
      preLoaderRoute: typeof DashboardUploadRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/streak': {
      id: '/dashboard/streak'
      path: '/streak'
      fullPath: '/dashboard/streak'
      preLoaderRoute: typeof DashboardStreakRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/stats': {
      id: '/dashboard/stats'
      path: '/stats'
      fullPath: '/dashboard/stats'
      preLoaderRoute: typeof DashboardStatsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/decks': {
      id: '/dashboard/decks'
      path: '/decks'
      fullPath: '/dashboard/decks'
      preLoaderRoute: typeof DashboardDecksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/create-youtube': {
      id: '/dashboard/create-youtube'
      path: '/create-youtube'
      fullPath: '/dashboard/create-youtube'
      preLoaderRoute: typeof DashboardCreateYoutubeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/create-notes': {
      id: '/dashboard/create-notes'
      path: '/create-notes'
      fullPath: '/dashboard/create-notes'
      preLoaderRoute: typeof DashboardCreateNotesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/connected-apps': {
      id: '/dashboard/connected-apps'
      path: '/connected-apps'
      fullPath: '/dashboard/connected-apps'
      preLoaderRoute: typeof DashboardConnectedAppsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/review/start': {
      id: '/dashboard/review/start'
      path: '/review/start'
      fullPath: '/dashboard/review/start'
      preLoaderRoute: typeof DashboardReviewStartRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/review/$deckId': {
      id: '/dashboard/review/$deckId'
      path: '/review/$deckId'
      fullPath: '/dashboard/review/$deckId'
      preLoaderRoute: typeof DashboardReviewDeckIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/deck/$deckId': {
      id: '/dashboard/deck/$deckId'
      path: '/deck/$deckId'
      fullPath: '/dashboard/deck/$deckId'
      preLoaderRoute: typeof DashboardDeckDeckIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing/history': {
      id: '/dashboard/billing/history'
      path: '/history'
      fullPath: '/dashboard/billing/history'
      preLoaderRoute: typeof DashboardBillingHistoryRouteImport
      parentRoute: typeof DashboardBillingRoute
    }
  }
}

interface DashboardBillingRouteChildren {
  DashboardBillingHistoryRoute: typeof DashboardBillingHistoryRoute
}

const DashboardBillingRouteChildren: DashboardBillingRouteChildren = {
  DashboardBillingHistoryRoute: DashboardBillingHistoryRoute,
}

const DashboardBillingRouteWithChildren =
  DashboardBillingRoute._addFileChildren(DashboardBillingRouteChildren)

interface DashboardRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRouteWithChildren
  DashboardConnectedAppsRoute: typeof DashboardConnectedAppsRoute
  DashboardCreateNotesRoute: typeof DashboardCreateNotesRoute
  DashboardCreateYoutubeRoute: typeof DashboardCreateYoutubeRoute
  DashboardDecksRoute: typeof DashboardDecksRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardStatsRoute: typeof DashboardStatsRoute
  DashboardStreakRoute: typeof DashboardStreakRoute
  DashboardUploadRoute: typeof DashboardUploadRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardDeckDeckIdRoute: typeof DashboardDeckDeckIdRoute
  DashboardReviewDeckIdRoute: typeof DashboardReviewDeckIdRoute
  DashboardReviewStartRoute: typeof DashboardReviewStartRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBillingRoute: DashboardBillingRouteWithChildren,
  DashboardConnectedAppsRoute: DashboardConnectedAppsRoute,
  DashboardCreateNotesRoute: DashboardCreateNotesRoute,
  DashboardCreateYoutubeRoute: DashboardCreateYoutubeRoute,
  DashboardDecksRoute: DashboardDecksRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardStatsRoute: DashboardStatsRoute,
  DashboardStreakRoute: DashboardStreakRoute,
  DashboardUploadRoute: DashboardUploadRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardDeckDeckIdRoute: DashboardDeckDeckIdRoute,
  DashboardReviewDeckIdRoute: DashboardReviewDeckIdRoute,
  DashboardReviewStartRoute: DashboardReviewStartRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiStudyToolForCollegeStudentsRoute: AiStudyToolForCollegeStudentsRoute,
  AnkiAlternativeRoute: AnkiAlternativeRoute,
  BestAiStudyAppRoute: BestAiStudyAppRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DeleteAccountRoute: DeleteAccountRoute,
  DocumentationMcpRoute: DocumentationMcpRoute,
  FlashcardGeneratorRoute: FlashcardGeneratorRoute,
  LoginRoute: LoginRoute,
  MedicalStudentStudyAppRoute: MedicalStudentStudyAppRoute,
  PdfToFlashcardsRoute: PdfToFlashcardsRoute,
  PrivacyRoute: PrivacyRoute,
  QuizletAlternativeRoute: QuizletAlternativeRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpacedRepetitionAppRoute: SpacedRepetitionAppRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  YoutubeToFlashcardsRoute: YoutubeToFlashcardsRoute,
  DecksDeckIdRoute: DecksDeckIdRoute,
  DownloadsPikadecksDotapkRoute: DownloadsPikadecksDotapkRoute,
  OauthConsentRoute: OauthConsentRoute,
  DecksIndexRoute: DecksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
